### ISSUE TITLE
Layer toggle is wonky

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapvue#32]
Probably there some element which isn't responding to the click handler; sometimes you click and "miss" the button.

**Comment by brucecrevensten** [comment]
This seems to only affect Firefox (on MacOS at least).

**Comment by BobTorgerson** [comment]
As it turns out, if you disable the "draggable" functionality from src/components/LayerList.vue, this works in Firefox, but you can no longer reorder the layers by dragging and dropping them. There is something that is preventing the spans from properly registering as part of the button while they have the drag and drop functionality.

**Comment by brucecrevensten** [comment]
Fixed don't need now that we have the GUI rework.
